FROM balenalib/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update -y && apt-get -y install curl build-essential vim pkg-config openssl libssl-dev
# RUN ln -s /usr/bin/gcc /usr/bin/arm-linux-gnueabi-gcc

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /root/.cargo/bin/rustup target install arm-unknown-linux-gnueabi

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /build

COPY . /build

RUN cargo build --release
