on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master # flowzonify 0.4.4
    secrets: inherit
    with:
      rust_binaries: true
      cargo_targets: |
        aarch64-unknown-linux-musl,
        armv7-unknown-linux-musleabihf,
        arm-unknown-linux-musleabihf,
        x86_64-unknown-linux-musl,
        i686-unknown-linux-musl
